token_telegram = "7239664206:AAFAttPwszOHct28eYWcxzg6TE2OitlauQY"
palabras_prohibidas = [
    "baboso",  
    "bastardo",
    "cabron",  
    "cabrones",
    "chcha",   
    "chucha",
    "cojudo",
    "conchetumadre",
    "hdp",
    "hijoputa",
    "hijue puta",
    "hijueputa",
    "huevon",
    "idiota",
    "imbecil",
    "mal parido",
    "malparida",
    "malparido",
    "mama huevo",
    "mamahuevo",
    "mierda",
    "mmvrg",
    "pelotuda",
    "pelotudo",
    "pendejo",
    "perra",
    "puta",
    "puta madre",
    "putamadre",
    "puto",
    "reflechucha",
    "soquete",
    "tarado",
    "verga",
    "vrg",
    "zorra"
]
